// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","termsOfService":"http://swagger.io/terms/","contact":{"name":"API Support","url":"http://www.swagger.io/support","email":"support@swagger.io"},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0.html"},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/product/new":{"post":{"description":"This resources is responsible for registering into database","consumes":["application/json"],"produces":["application/json"],"tags":["Product"],"summary":"Register a product in database","parameters":[{"description":"Product Body","name":"productBody","in":"body","required":true,"schema":{"$ref":"#/definitions/request.Product"}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/response.Created"}},"400":{"description":"Bad Request","schema":{"$ref":"#/definitions/response.Error"}},"404":{"description":"Not Found","schema":{"$ref":"#/definitions/response.Error"}},"500":{"description":"Internal Server Error","schema":{"$ref":"#/definitions/response.Error"}}}}}},"definitions":{"request.Product":{"type":"object","properties":{"code":{"type":"string"},"name":{"description":"utiliza de bandeiras em go (associar os atribuots de um json aos atributos de produto)","type":"string"},"price":{"type":"number"}}},"response.Created":{"type":"object","properties":{"id":{"type":"integer"}}},"response.Error":{"type":"object","properties":{"msg":{"type":"string"},"statusCode":{"type":"integer"}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Padaria API",
	Description:      "This is an example backery server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
