basePath: /api
definitions:
  request.Product:
    properties:
      code:
        type: string
      name:
        description: utiliza de bandeiras em go (associar os atribuots de um json
          aos atributos de produto)
        type: string
      price:
        type: number
    type: object
  response.Created:
    properties:
      id:
        type: integer
    type: object
  response.Error:
    properties:
      msg:
        type: string
      statusCode:
        type: integer
    type: object
host: localhost
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an example backery server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Padaria API
  version: "1.0"
paths:
  /product/new:
    post:
      consumes:
      - application/json
      description: This resources is responsible for registering into database
      parameters:
      - description: Product Body
        in: body
        name: productBody
        required: true
        schema:
          $ref: '#/definitions/request.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Created'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Register a product in database
      tags:
      - Product
swagger: "2.0"
